version: 2.1
orbs:
    cypress: cypress-io/cypress@1
jobs:
    node-12:
        docker:
            - image: circleci/node:12
        working_directory: ~/paper-wallet
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
                      - v1-deps-{{ .Branch }}
                      - v1-deps
            - run:
                  name: Install Dependencies
                  command: yarn install --frozen-lockfile
            - save_cache:
                  paths:
                      - ~/.cache
                  key: v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - run:
                  name: Build
                  command: yarn build
            - run:
                  name: Unit Tests
                  command: yarn test:unit
            - run:
                  name: Codecov
                  command: ./node_modules/.bin/codecov
workflows:
    build:
        jobs:
            - cypress/run:
                  yarn: true
            - node-12
