version: 2.1
jobs:
    node-12:
        docker:
            - image: circleci/node:12
        working_directory: ~/paper-wallet
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
                      - v1-deps-{{ .Branch }}
                      - v1-deps
            - run:
                  name: Install System Dependencies
                  command: sudo apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
            - run:
                  name: Install Application Dependencies
                  command: yarn install --frozen-lockfile
            - save_cache:
                  paths:
                      - ~/.cache
                  key: v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - run:
                  name: Build
                  command: yarn build
            - run:
                  name: Unit Tests
                  command: yarn test:unit
            - run:
                  name: E2E Tests
                  command: yarn test:e2e:ci
            - run:
                  name: Codecov
                  command: ./node_modules/.bin/codecov
workflows:
    build:
        jobs:
            - node-12
